### ISSUE TITLE
How do I send a message?

### ISSUE THREAD

**Issue by nerdDan** [nestjs-community/nestjs-amqp#15]
I do not find such code in unit tests.

**Comment by bashleigh** [comment]
This package is a bit of a work in process. It uses the [amqplib](https://www.npmjs.com/package/amqplib) package that has some docs on how to use it. I've used this module similar to this:

#### AppModule
```ts
import {Module} from '@nestjs/common';
import {AmqpModule} from 'nestjs-amqp';
import TestProvider from './test.provider';
import TestController from './test.controller';

@Module({
  imports: [
    AmqpModule.forRoot({
      host: 'amqp://localhost:5672',
    }),
  ],
  controllers: [
    TestController,
  ],
  providers: [
    TestProvider,
  ],
})
export default class AppModule {}
```
#### TestProvider
```ts
import {Injectable, Logger} from '@nestjs/common';
import {InjectAmqpConnection} from 'nestjs-amqp';

@Injectable()
export default TestProvider {
  constructor(@InjectAmqpConnection() private readonly amqp) {}
  async publish(message: string)  {
    await this.amqp.createChannel((err, channel) => {
      if (err != null) {
        Logger.alert(err, 'TestProvider');
      }
      channel.assertQueue('test_queue_name');
      channel.sendToQueue('test_queue_name', message);
    });
  }
}
```
#### TestController
```ts
import {Controller} from '@nestjs/common';
import TestProvider from './test.provider';

@Controller()
export default TestController {
  constructor(private readonly testProvider: TestProvider) {}
  @Get('test')
  async example() {
    await this.testProvider.publish('I am a message');
  }
}
```

I'm making some implementation improvements to the package so if there's anything you think I should add to make it easier to work with let me know. I do want to implement a class and some decorators for easier integration https://github.com/nestjs-community/nestjs-amqp#future-implementation

**Comment by nerdDan** [comment]
Wow! Thank you for your amazing work! Can't wait to see the finished version!

**Comment by bashleigh** [comment]
No problem :) did you get it working?

**Comment by nerdDan** [comment]
No. Actually I have another question. How do I make AMQP host (`amqp://localhost:5672`) in the config file? I do not see a `useFactory` method.

**Comment by bashleigh** [comment]
You mean like this? 

```ts
AmqpModule.forRoot({
      host: 'amqp://localhost:5672',
    }),
```

Or as in a configurable way? I'm currently implementing a forRootAsync() with a async config setup. I just haven't managed to get the tests to pass (think there's an open connection which I literally just found!). You can use an ENV with the current master version 0.0.5 but it's requires some hack-iness to get it running correctly. 

```
AMQP_HOST=192.168.99.100
AMQP_PORT=5672
AMQP_USERNAME=guest
AMQP_PASSWORD=guest
```

The above envs 'should' work (specified here https://github.com/nestjs-community/nestjs-amqp/blob/master/src/config/amqp.ts). However you've got the run dotenv or whatever before your module load to get this working. I do have a new branch I've been working on. Now that the tests pass (as I was typing this) I can continue with resolving the configs and create a forRootAsync version :)

**Comment by nerdDan** [comment]
Got it! Thank you again!

**Comment by bashleigh** [comment]
If you're interested, in the `feature/module-implementation-update` I've just added the `forRootAsync` method. Unfortunately it will only work for one method as I can't dynamically make the options and connections after the factory call which is annoying but the default options work :) 
https://github.com/nestjs-community/nestjs-amqp/commit/a80f2ac5493e9e5cdfaec05db79de9374258e302
