### ISSUE TITLE
Inject connection to factory

### ISSUE THREAD

**Issue by Patrick-Remy** [nestjs-community/nestjs-amqp#21]
Is it possible to inject the AmqpConnection in a factory of a custom provider? 

I tried this but without success:
```ts
import { Connection as AmqpConnection } from 'amqplib'
import { ConfigService } from 'nestjs-config'

export const queueServiceProvider = {
  provide: 'QueueService',
  useFactory: (amqp: AmqpConnection, configService: ConfigService) => {
    return new QueueService(amqp, configService.get('queue'))
  },
  inject: [AmqpConnection, ConfigService]
}
```

**Comment by bashleigh** [comment]
Yes it's possible. The problem with the nestjs-amqp package is when having multiple connections you need unique tokens so I made a constant which has a int on the end like `AMQP_CONNECTION_PROVIDER_0` or if one connection is present (or using the forRootAsync) I used 'default'. If you see [here](https://github.com/nestjs-community/nestjs-amqp/blob/master/src/amqp.module.ts#L51) I made a function that does all this so you could inject the provider using the token instead like so 

```typescript
import {ConfigService} from 'nestjs-config';
import {createConnectionToken} from 'nestjs-amqp/utils';

export const queueServiceProvider = {
    provider: 'QueueService',
    useFactory: (amqp, configService: ConfigService) => new QueueService(amqp, configService.get('queue),
    inject: [createConnectionToken('default'), ConfigService],
}
```

**Comment by bashleigh** [comment]
If you would like to make a PR to add this to the read me feel free! :)
