### ISSUE TITLE
Can not resolve dependencies

### ISSUE THREAD

**Issue by da-wolf** [nestjs-community/nestjs-amqp#26]
I tried to send a message, like described [here](https://github.com/nestjs-community/nestjs-amqp/issues/15), but I'm getting the following error: 

> [ExceptionHandler] Nest can't resolve dependencies of the AppAmqp (?). Please make sure that the argument at index [0] is available in the AppModule context. +25ms

This is my provider:

```ts
import {Injectable, Logger} from '@nestjs/common';
import {InjectAmqpConnection} from 'nestjs-amqp';

@Injectable()
export class AppAmqp {
    constructor(@InjectAmqpConnection() private readonly amqp: any) {}
    async publish(message: string)  {
        await this.amqp.createChannel((err, channel) => {
            if (err != null) {
                Logger.warn(err, 'TestProvider');
            }
            channel.assertQueue('test_queue_name');
            channel.sendToQueue('test_queue_name', message);
        });
    }
}

```
And here is the AppModule

```ts
import { Module } from '@nestjs/common';
import { AmqpModule } from 'nestjs-amqp';
import { AppController } from './app.controller';
import { AppAmqp } from './app.amqp';

@Module({
    imports: [AmqpModule.forRoot({
        hostname: 'localhost',
        port: 5672,
    })],
    controllers: [AppController],
    providers: [AppAmqp],
})
export class AppModule {}

```
Controller:
```ts
@Controller()
export class AppController {
  constructor(
      private readonly appAmqp: AppAmqp,
  ) {}

  @Get('/:name')
  async root(@Param('name') name): Promise<string> {
    await this.appAmqp.publish(name);
  }
}
```

What am I missing?

**Comment by bashleigh** [comment]
I think this will be related to how the amqp module is setup. I reckon it passes the tests in this instance because I've added an `await app.init()` in the bootstrap. 

For now though, try `forRootAsync` and I'll look into this

**Comment by kjetilhp** [comment]
I'm having the exact same issue using the forRootAsync when trying to inject config

Works with sync and no config inject with the provider receipt though.

(commented out the config inject to see if that was the problem but still getting the error, tried with both async app.init and no init in bootstrap with same result..)

Q: anyway you could release some complete sample code that you know works and not only the snippets in the readme? if we are doing stuff wrong I mean

Code:
```
import { AmqpModule } from 'nestjs-amqp'
// import { ConfigModule, ConfigService } from '@catalog/shared.nest'
import { MessagingService } from './messaging.service'
import { Module } from '@nestjs/common'

@Module({
  imports: [
    MessagingService,
    // ConfigModule,
    AmqpModule.forRootAsync({
      useFactory: async () /*(configService: ConfigService)*/ => {
        return Promise.resolve({
          name: 'rabbitmq',
          hostname: 'localhost',
          port: 5672,
          username: 'guest',
          password: 'guest',
        })
      },
      // inject: [ConfigService],
    }),
  ],
  exports: [MessagingService],
})
export class MessagingModule {}
```

```
import { Injectable } from '@nestjs/common'
import { InjectAmqpConnection } from 'nestjs-amqp'

@Injectable()
export class MessagingService {
  constructor(@InjectAmqpConnection('rabbitmq') private readonly amqp) {}
}
```
```
Error
[Nest] 25025   - 2/13/2019, 9:07:20 PM   [ExceptionHandler] Nest can't resolve dependencies of the MessagingService (?). Please make sure that the argument at index [0] is available in the MessagingService context. +22ms
Error: Nest can't resolve dependencies of the MessagingService (?). Please makesure that the argument at index [0] is available in the MessagingService context.
    at Injector.lookupComponentInExports (/Users/kjetil/devwork/catalog/catalog-app/node_modules/@nestjs/core/injector/injector.js:144:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
[Nest] 25025   - 2/13/2019, 9:07:20 PM   [InstanceLoader] MessagingModule dependencies initialized +0ms
 1: 0x10003ae75 node::Abort() [/Users/kjetil/.nvm/versions/node/v10.13.0/bin/node]

```

**Comment by bashleigh** [comment]
Ok, so I think I worked out why this happens. The amqp connection providers are created asynchronously. Therefore not existing when you create your providers `AppAmqp` and `MessagingService`. 

In both instances you'd both have to do this to resolve your issue. 

```ts
@Module({
  imports: [
    AmqpModule.forRoot({
      name: 'test',
   }),
  ],
  providers: [
    {
      provide: MessagingService,
      useFactory: async (connection: Connection) => new MessagingService(connection),
      injects: [createConnectionToken('test'),
    },
  ],
})
export class ...
```

Which is a bit of a naff fix. I have been thinking of creating a manager class as an injectable which you can inject and that itself sets up the connections etc that you need.

**Comment by kjetilhp** [comment]
the createConnectionToken(..) method isn't exported from the package

**Comment by bashleigh** [comment]
@kjetilhp no but you should be able to access it like so 

```ts
import {createConnectionToken} from 'nestjs-amqp/utils';
```

**Comment by kjetilhp** [comment]
like this `import { createConnectionToken } from 'nestjs-amqp/dist/utils/create.tokens'` works
(also, config above should be inject without the s)
anyway, this works when using the forRoot but not with forRootAsync, which was my goal so I could inject the config service, not having to hardcode the config.

**Comment by bashleigh** [comment]
So does `forRootAsync` work when using a synchronous method for `useFactory` but not when using an asynchronous method?

**Comment by bashleigh** [comment]
Also, I've just realised that the `forRootAsync` method will only ever create a connection called default and will ignore the `name` key passed to the options. Sorry I forgot about that

**Comment by kjetilhp** [comment]
Changing all names to default helped, so this works:

```
import { AmqpModule } from 'nestjs-amqp'
import { ConfigModule, ConfigService } from '@catalog/shared.nest'
import { MessagingService } from './messaging.service'
import { Module } from '@nestjs/common'
import { Connection } from 'amqplib'
import { createConnectionToken } from 'nestjs-amqp/dist/utils/create.tokens'

@Module({
  imports: [
    ConfigModule,
    AmqpModule.forRootAsync({
      useFactory: async (configService: ConfigService) => {
        return configService.rabbitConfig()
      },
      inject: [ConfigService],
    }),
  ],
  providers: [
    {
      provide: MessagingService,
      useFactory: async (connection: Connection) => new MessagingService(connection),
      inject: [createConnectionToken('default')],
    },
  ],
  exports: [MessagingService],
})
export class MessagingModule {}

import { Injectable } from '@nestjs/common'
import { InjectAmqpConnection } from 'nestjs-amqp'

@Injectable()
export class MessagingService {
  constructor(@InjectAmqpConnection('default') private readonly amqp) {}
}

```

**Comment by kjetilhp** [comment]
> So does `forRootAsync` work when using a synchronous method for `useFactory` but not when using an asynchronous method?

works with booth, seems that naming was the issue

**Comment by kjetilhp** [comment]
also works with just 
`providers: [MessagingService],`
no need for the extra providers config

**Comment by bashleigh** [comment]
Cool :) Glad that fixed your issue! 

However I think the original issue still persists with the controller injection with forRoot. I'll look into that when I can

**Comment by kjetilhp** [comment]
Think maybe that also is related to the naming/default connection, I think I had the same issue when not naming my connection something and trying to use the decorator with no argument.

**Comment by bashleigh** [comment]
Closing this issue as I don't think there's an open issue anymore with the package. The original issue was resolved by `forRootAsync`. The dependancy on AppAmqp was unable to find the async provider due to how nestjs modules are setup
