### ISSUE TITLE
Error in module config of module

### ISSUE THREAD

**Issue by kjetilhp** [nestjs-community/nestjs-amqp#27]
Following the steps in the readme result in type errors
```
AmqpModule.forRoot({
      name: 'rabbitmq',
      hostname: 'localhost',
      port: 5672,
      username: 'guest',
      password: 'guest',
    })
```
ERROR in app.module.ts(41,7):
TS2345: Argument of type '{ name: string; hostname: string; port: number; username: string; password: string; }' is not assignable to parameter of type 'AmqpOptionsInterface | AmqpOptionsInterface[]'.
  Object literal may only specify known properties, and 'hostname' does not exist in type 'AmqpOptionsInterface | AmqpOptionsInterface[]'.

Seems that it can't resolve the inherited Options from amqplib, somethink I'm missing here?

**Comment by bashleigh** [comment]
hmm that's odd. I shall check this out when I can!

**Comment by kjetilhp** [comment]
same problem, only excepts the options not inherited from amqlib

**Comment by bashleigh** [comment]
what ts version are you using out of interest?

**Comment by kjetilhp** [comment]
3.2.2

**Comment by kjetilhp** [comment]
after installing the @types/amqplib package in my project it works

**Comment by bashleigh** [comment]
@kjetilhp Can you try using v0.1.3 for me? See if that fixes your problem?

**Comment by kjetilhp** [comment]
seems to work now :)

btw, I had to rewrite the send method that is used as an example in the readme to get it to send, not sure if that have to do with versions of libs but in my code the execution never got into the createChannel method
(yeah, this is publish but same create method)
```
const channel = await this.amqp.createChannel()
channel.publish('catalog.direct', '', Buffer.from(JSON.stringify(message)))
```
also have some issues with the async config but I'll post that in another issue

this can be closed

**Comment by bashleigh** [comment]
Cool thanks for checking that out. Yea the amqplib connection can be used anyway you want really. This is the documentation https://www.npmjs.com/package/amqplib for amqplib. I think this package has been made redundant in most cases by the transport for rabbitMQ https://docs.nestjs.com/microservices/rabbitmq however I use this package for event consumers etc so it depends what you use it for really. If there's anything else, please let me know!

**Comment by rdrahul** [comment]
Is this resolved? I am still facing the same problem. I am using v0.1.3 and  typescript 3.4.5

**Comment by bashleigh** [comment]
@rdrahul can you send me an example of your implementation please? I think `host` became `hostname` or the other way around.

**Comment by lesimoes** [comment]
@rdrahul are u use variables from env file? Seems like typescript has a problem with them. 
Try something like this:

```typescript
const host = `${process.env.HOST}`;
const port = Number(process.env.PORT)

AmqpModule.forRoot({
 host,
 port,
});
`
