### ISSUE TITLE
Connecting to amqp failing

### ISSUE THREAD

**Issue by pratikpanchal4472** [nestjs-community/nestjs-amqp#31]
![image](https://user-images.githubusercontent.com/8873622/56820080-aa073f80-6868-11e9-85ba-26a01c85cdfa.png)

Getting this error while starting up nest application.

![image](https://user-images.githubusercontent.com/8873622/56820158-cacf9500-6868-11e9-9f92-c6659f32955a.png)

What am I missing?

**Comment by bashleigh** [comment]
My guess would be your amqp server is unreachable? Could you provide your setup? Like is this a docker integration or?

**Comment by bashleigh** [comment]
I'm going to close this issue as I don't think this is an issue with the nestjs-amqp package. Let me know if there is an issue with the package. Thanks :)
